### ISSUE TITLE
Can't apply a theme to a Candle Colour

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons-core#6]
If you try and apply a theme using `lifx:apply_theme` to a Candle Colour bulb, it breaks trying to find the chain information:

```
$ lifx lan:apply_theme d073d5xxxxxx -- '{"colors": [ "red", "blue", "green", "yellow" ], "theme": "SPLOTCH"}'
...
16:57:54 INFO    photons_themes  found a device with matrix zones	serial=d073d5xxxxxx
16:57:54 ERROR   photons_app.helpers 'type' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/photons_control/script.py", line 407, in getter
    msg = await gen.asend(complete)
  File "/usr/local/lib/python3.7/site-packages/photons_themes/addon.py", line 124, in gen
    async for m in instance.apply(info["cap"]):
  File "/usr/local/lib/python3.7/site-packages/photons_themes/addon.py", line 154, in apply
    async for m in self.tile_msgs():
  File "/usr/local/lib/python3.7/site-packages/photons_themes/addon.py", line 183, in tile_msgs
    chain = info["chain"]
TypeError: 'type' object is not subscriptable
16:57:54 ERROR   photons_themes  'type' object is not subscriptable
```

**Comment by delfick** [comment]
Right, I see what's happening

tile_msgs is used when the device has the matrix capability, but then I use a plan that depends on the chain capability and so for a candle `info` is `Skip` at that point because candle has matrix but not chain.

I'll fix this properly maybe tomorrow. In the meantime, the minimum hack you can do is change https://github.com/delfick/photons-core/blob/master/photons_control/planner/plans.py#L372 to look at `has_matrix` instead of `has_chain`.

**Comment by Djelibeybi** [comment]
I can wait (and it doesn't need to be tomorrow either: fix it at work). :)

**Comment by delfick** [comment]
I've started this branch https://github.com/delfick/photons-core/compare/improvechainplan

Just have to write tests at some point in the future and then I'll put it in master.

**Comment by Djelibeybi** [comment]
FYI, it works for me. :) Thanks!

**Comment by delfick** [comment]
Ok, 0.24.6 released with this fix
